=== javsalgar/session-maker-for-spotify/schema.json
{
  "$id": "https://example.com/spotify_session_maker.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Session",
  "type": "object",
  "required": [
    "title",
    "maxSongs",
    "sources",
    "pattern"
  ],
  "additionalProperties": false,
  "properties": {
    "title": {
      "type": "string",
      "description": "Session title. Will be translated to a Spotify playlist"
    },
    "description": {
      "type": "string",
      "description": "Session description"
    },
    "spotifyID": {
      "type": "string",
      "description": "Existing playlist Spotify ID"
    },
    "maxSongs": {
      "type": "integer",
      "description": "Maximum amount of songs to use in the playlist, if one of the playlists cannot fulfill it, it will stop"
    },
    "sources": {
      "type": "array",
      "description": "Source playlist groups to build the session.",
      "items": {
        "$ref": "#/$defs/playlistGroup"
      }
    },
    "pattern": {
      "description": "Pattern to use from the source playlists to build the session.",
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "$defs": {
    "playlistGroup": {
      "type": "object",
      "required": [
        "name",
        "spotifyIDs"
      ],
      "properties": {
        "name": {
          "type": "string",
          "description": "Name to identify the playlist group"
        },
        "spotifyIDs": {
          "type": "array",
          "description": "IDs inside Spotify of the playlists",
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== javsalgar/session-maker-for-spotify/examples/swing_session.json
{
  "title": "Swing session by BPMs and 10% Blues",
  "description": "Built with spotify-session-maker",
  "maxSongs": 200,
  "sources": [
    {
      "name": "100-120",
      "spotifyIDs": [
        "7ivzWZParGOFfg6WLurw8E"
      ]
    },
    {
      "name": "120-140",
      "spotifyIDs": [
        "57TmdQaIAxm142Kec2xFrX"
      ]
    },
    {
      "name": "140-160",
      "spotifyIDs": [
        "0V1aG0b9ye5B4MPId1Znj7"
      ]
    },
    {
      "name": "160-180",
      "spotifyIDs": [
        "0Ky3d8TBOOe4VYd0AodaTL"
      ]
    },
    {
      "name": "Over180",
      "spotifyIDs": [
        "3IO3m6mfuDLvBrkpllHlJ6",
        "1nDCfIMWHQDpChhitrI0sk"
      ]
    },
    {
      "name": "Blues",
      "spotifyIDs": [
        "7kwIt9o0BTtszsl3VVtHPT"
      ]
    }
  ],
  "pattern": [
    "100-120",
    "120-140",
    "140-160",
    "160-180",
    "Over180",
    "100-120",
    "120-140",
    "140-160",
    "160-180",
    "Blues"
  ]
}
